In [2]:
import numpy as np

In [6]:
x = np.array([40,67,57,90])
print(x)
print(type(x))
print(x.dtype)

[40 67 57 90]
<class 'numpy.ndarray'>
int32


In [10]:
x = np.array(['A',67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

['A' '67' '57' '9.8']
<class 'numpy.ndarray'>
<U32


In [14]:
#Create a 2D Array
a2 = np.array([[20,40],[30,60]])
print(a2)
print(type(a2))
print(a2.shape)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
(2, 2)


In [16]:
#Reshaping the Array
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [18]:
a = np.array([10,20,30,40])
b = a.reshape(3,2)
print(b)
print(b.shape)

ValueError: cannot reshape array of size 4 into shape (3,2)

In [20]:
a = np.array([10,20,30,40])
b = a.reshape(2,3)
print(b)
print(b.shape)

ValueError: cannot reshape array of size 4 into shape (2,3)

In [24]:
#Create an array with arrange()
c = np.arange(3,20)
print(c)
type(c)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [26]:
#Create an array with arrange()
c = np.arange(1,5)
print(c)
type(c)

[1 2 3 4]


numpy.ndarray

In [28]:
#Use of around() (to around figure the values of decimals)
d = np.array([1.3467,3.10987,4.91236])
np.around(d,2)

array([1.35, 3.11, 4.91])

In [30]:
#Use of np.sqrt()
print(np.sqrt(d))

[1.16047404 1.76348235 2.21638444]


In [32]:
a = np.array([100,25,36,49,10000])
print(np.sqrt(a))

[ 10.   5.   6.   7. 100.]


In [34]:
np.around(a)

array([  100,    25,    36,    49, 10000])

In [36]:
print(np.around(np.sqrt(d),2))

[1.16 1.76 2.22]


In [46]:
#Use astype() to convert the data type
a1 = np.array([[3,4,5,8],[7,2,8,np.NaN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [48]:
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [55]:
#Mathematical operations on rows and columns
a2 = np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [53]:
print(a2.sum(axis = 1))
print(a2.sum(axis = 0))

[13 26 22]
[14 19 28]


In [57]:
np.sqrt(a2)

array([[1.73205081, 2.        , 2.44948974],
       [2.64575131, 3.        , 3.16227766],
       [2.        , 2.44948974, 3.46410162]])

In [61]:
#Mean Values along rows and col
print(a2)
print(np.mean(a2,axis=1))
print(np.mean(a2,axis=0))

[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]
[4.33333333 8.66666667 7.33333333]
[4.66666667 6.33333333 9.33333333]


In [65]:
#Matrix operations
a3 = np.array([[3,4,6],[7,9,10],[4,6,12]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]
[[ 0  4  6]
 [ 7  0 10]
 [ 4  6  0]]


In [69]:
#Define two matrices and multiply them
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

#Perform matrix multiplication
C = np.matmul(A,B)
print(C)

[[19 22]
 [43 50]]


In [71]:
#Print the Transpose of the matrix
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [73]:
#Accessing the array elements
a4 = np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])
a4

array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  1,  6],
       [10,  9, 18]])

In [75]:
#Indexing of rows and columns start with 0
a4[1][1]

2

In [81]:
a4[3][2]

18

In [83]:
a4[:,1:]

array([[ 4,  5],
       [ 2,  8],
       [ 1,  6],
       [ 9, 18]])

In [87]:
a4[1:3,:2]

array([[7, 2],
       [9, 1]])